services:
  nextjs-app:
    build:
      context: . # Ensure this is the correct path to your project root
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    secrets:
      - OPENAI_API_KEY
secrets:
  OPENAI_API_KEY:
    file: .env.local